### ISSUE TITLE
New Emails for Thomas, President and Newsletter

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#1]
Need three new Emails:

Thomas@recoverydharma.org - connected to anthomas@gmail.com
newsletter@recoveryhdarma.org - connected to paul@recoverydharma.org
president@recoverydharma.org - connected to kris@recoverydharma.org

Newsletter and President will be permanent emails. They will be utilized by a team and/or by whomever is the current holder of the office.  The content and archives of those emails will stay with the position so that new volunteers will have access to the history of that position. 

Accepting suggestions on how to best configure that need. 

Kris

**Comment by KrisRecoveryDharma** [comment]
Please go forward with Thomas' email.

**Comment by catpanclub** [comment]
Kris - a few points before this is wrapped up.
 - Thomas has been added to the Suite
 - We've been using a newsletter@recoverydharma.org email account for quite awhile; credentials are in 1Password
 - Happy to create a president@ account, but new profile accounts of any type have to be tied to a NON-RD account. They must be tied to a personal email account (Gmail, to be more specific), and this is why we've resisted creating a plethora of these generic accounts. Nonetheless, it's fine to do so, and as personnel change I'll (or whomever has super-admin privileges) will have to go in and reset the password and redirect ownership of the account.

If you want the president@ profile tied to you, then, just let me know what external, personal Gmail account to which I can connect it.

**Comment by KrisRecoveryDharma** [comment]
Thank you for the reminder about the newsletter email.  Who is that sent to now?  It needs to be changed to Paul. 

Yes, please create a President alias.   For now, keep it tied to roehlkris@gmail.com

Thanks!

Kris

**Comment by catpanclub** [comment]
Kris - any emails coming into the newsletter account email are not sent to (or forwarded to) anyone. Again, the credentials are in 1Password, so Paul can log in and have those emails forwarded to him or another place if he prefers. I've been checking it occasionally over the past few months since no one else has assumed responsibility. There has been zero traffic since I sent an email to the "summer" contributors letting them know that the board was taking a pause. 

I will create the other G Suite profile for you - please remember to log in and change your password in a timely manner so the account doesn't reset to inactive. You should get an email at your personal Gmail this morning.

**Comment by KrisRecoveryDharma** [comment]
I'm all set up with the new email. Thanks!

Thank you for helping me understand all of this.  I apologize for the repeat questions. I am looking forward to the written version so I can try that first. 

If all RD emails need to be associated with a user, whose non-rd email is the newsletter alias connected to?

**Comment by catpanclub** [comment]
Right - the newsletter@ profile (along with some of the other generic profiles - but not all) are tied to me. When I began working with the prior board and transition team around July of last year, the intention was to ground accounts like those with an individual who was not a board member (allowing the board to focus more on strategic and less on administrative issues), and also with someone who had capacity and a willingness to stick with this for more than just short-term (given the rapid rate of turnover we continue to see at the volunteer level).

Long answer to basically say "me," but in the hopes the additional context helps.

**Comment by unity1979** [comment]
(note: thomas@recoverydharma.org is 100% working 🙏)

**Comment by KrisRecoveryDharma** [comment]
Thank very helpful

**Comment by KrisRecoveryDharma** [comment]
New emails have been created. 

There is an ongoing discussion about the policy for assigning Recovery Dharma Emails.  For now, though, this particular topic is closed. 

Thank you!
Kris
