### ISSUE TITLE
Allow Lacey to designate assignees in GitHub

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#10]
Hey Sean,

I just realized that Lacey is not able to click on "assignees" for Git Hub issues.  Could we add her to the list?

Thanks!

Kris

**Comment by nutjob4life** [comment]
Added `Lacey-boop` to team `web` (which has full access to `website` repository).

**Comment by KrisRecoveryDharma** [comment]
Closed
