### ISSUE TITLE
Need lists all recovery dharma email accounts and slack channels. 

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#2]
Need documents that are accessible in the google drive of all of the Recovery Dharma Email and Slack Channels.

**Comment by nutjob4life** [comment]
Just FYI, we can make wikis here on GitHub if Google Drive gets over-crowded

**Comment by KrisRecoveryDharma** [comment]
That is an interesting option.  I want to hear more. We have been talking about having a regular Website team meeting. Now that we have an emerging three teams, we can organize the meetings that way.  So - let's see if we can come up with a regular monthly meeting time. Is there a regular day of the week that is better for folks that we could schedule an Infrastructure IT meeting around?   Tuesday, Thursday & Friday evenings - and weekends are best for me.

**Comment by catpanclub** [comment]
I have a list of RD GSuite user accounts [here](https://docs.google.com/document/d/14HpnCYF19uuVP2xDtMDcxEsC6VDx6j5usVTlzy6UUxQ/edit?usp=sharing). I'll add more detail (like owner) as I have time.

Regarding a list of all Slack channels - not possible at this time, and generally not feasible on our plan. The only channels a user can see/access (including the owner of the Slack account, which is the admin@ profile, but also neither Lacey nor myself as admins) are those channels to which they have been added. 

The only way around this is to request an export of all data, and for that we'd need to provide (a) valid legal process, (b) consent of members, or (c) a requirement or right under applicable laws.

I'm not sure if you want to close this at this time, or leave it open, but that's a privacy feature of Slack, so here we are.

**Comment by KrisRecoveryDharma** [comment]
Thank you for the GSuite user accounts!  That is a great start. The next step is a spreadsheet with more detail.  As the board, we are responsible for overseeing who is using our assets. 

Having a list of the channel names on the channel that we own would not violate privacy. I'm not, in this request, asking for names or access to the channels. I might in the future, which may mean it is easier to become an administrator. For now, though, I want to give the board a list of the channels that are on our slack. We are in the midst of reviewing how we engage with slack. This is a basic snapshot that we need to review our asset.

**Comment by catpanclub** [comment]
Kris - I understand, but the same restrictions apply. I didn't think you were looking for a download of all data, but the underlying point is that there is no way to obtain a list of channels as admin or owner, under our current Slack plan.

The only way to get close to this is to ask the #everyone channel to supply a list of any Slack channels they may have created/are managers of. Based on my experience with that channel, it'd be far from complete.

I understand and honor the intention here, but I (nor any other single Slack user) cannot pull a list of the channels currently active under the rdcollective.slack account.

**Comment by KrisRecoveryDharma** [comment]
Okay, thank you for the clarity.   It sounds like we need a review of which plan we are using and what options are available to us.

**Comment by KrisRecoveryDharma** [comment]
List of GSuite User Names is complete. 
Closing Issue. 
Thanks!
Kris
