### ISSUE TITLE
Create 3 Drives:  Board, Committees and Public

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#3]
Please create three drives:

- Board:  to be accessed only by elected board members

- Committees - to be access by all board member, committee members and their volunteers

- Public - container for all publicly accessible documents.

**Comment by catpanclub** [comment]
Hi Kris - just a few questions/comments:

1. Board drive - this already exists, correct? The Recovery Dharma Shared/Team Drive, including a more secure folder as I recall, containing confidential documents.

2. Committees - I've already done this, and named it "Dharma Drive" (shoutout to @nutjob4life). Adding new people as they roll on to committees and removing them in the opposite case will be a manual process, just FYI.

Also on #2, as I said it exists but I haven't added anyone to it yet. I will add the board, and this committee. For additional people, I'd suggest we implement a process to notify them first, so they know to expect a random email from Google.

3. Public - this also really already exists. There is a folder (link below) set up under the Admin user profile's Drive that is entirely open to the public - **view only**. It is where we used to keep all the Google docs and PDFs we linked to on our website, before moving over to storing them in WordPress. I could easily archive all that information and start with a clean folder. Here's that folder: https://drive.google.com/drive/u/1/folders/1kHGq-xc6A-fGW5YUEul8qfWKLBDvMaKB

Please let me know your thoughts. Thank you!

**Comment by KrisRecoveryDharma** [comment]
Hey!

Sorry, I just now saw this.
1.  Yes, it does already exist.  Just articulating the structure
2. Darma Drive sounds like a great name.  Yes, notifying first is a good
idea.  I'll check in with the rest of the board on Tuesday and then we can
start adding the board and notifying / adding the Information Tech Team as
well as the placeholder emails.
3. I thought there was a public drive!  Now I have new questions.

   - I see that it is admin, but which person is it connected to?
   - Who has editing privileges?
   - Definitely either need it to be a shared drive among the board or we
   need a training so that board and committee members can find it easily and
   regularly.

Thank you!

Kris

**Comment by catpanclub** [comment]
I'm going to answer #3 first - that is set at the folder level, so it varies. There is one folder - "Public Resources" - that is completely open to read-only. Anyone with a link can open the files in that folder, and technically they could show up in a Google search result list, though it's highly unlikely. It's the only setting that allowed us at the beginning to make files (PDFs) quickly available to the community online.

All the other folders in that drive are set at folder-level security. Someone logged in as the Admin account would create a folder, and then add people to it depending on the purpose. So, there's a folder for the 2020 Conference, and everyone who worked on the committee at some point had/has access to it.

There are also some folders in that drive that are archived user files from when I've deleted Google Suite Users. They are likely useless.

Finally - the drive is connected to the admin@recoverydharma.org profile. I am the secondary owner of that account.

I've added this team to the Dharma Drive. I'll add the rest of the Board once they know what it's all about. Just a few things on that, if you don't mind:

People have to be added one at a time. In the event of adding several (as in adding this team), they all are given the same access role. You are all content managers, which means you can add, view, delete, edit, basically everything but you can't add people to the drive. Again, one at a time.

So, member management is an unfortunate consequence of this approach. Now once you have people in the system, it's easy to change their security role. But the board will have to decide how access to this drive is granted, i.e. who administers it.

On a somewhat related note, I know the board has decided to restrict access to RD Google Suite user profiles (emails) to just the board. The argument I'd make for extending those to people who work closely with board assets (my role, but also WordPress access, Mailchimp, so on) is security. If someone does goes off the rails, access to any of those assets can be immediate and thorough on our end by removing the profile. If people use their personal email accounts to log in to WordPress to do work for the board, you relinquish that security.

**Comment by KrisRecoveryDharma** [comment]
Thank you Dirk! This is helpful.

Yes!  agreed that it is a good idea to have some support accounts.  I think
the naming convention would be the thing. So, instead of
Dirk@recoverydharma.org,  it would be something like IT@recoverydharma.org
- or security@ or something appropriate.

Thank you for the breakdown of the drive security features.  It's looking
like we will need a flowchart type map of these folders and drives.  Well,
I guess I need one - I'm a spacial thinker.

Thank you again!

**Comment by KrisRecoveryDharma** [comment]
Okay, I think I have wrapped my brain around it:

1. Everything goes into Recovery Dharma Drive
2. Folders are created according to Board Committees all documents are sorted into one of those folders
3. Drive is set to "anyone on team" level permission to edit
4. Board members are added to the top-level folder team
4. Committee members and volunteers are added at the committee or team folder level.
5. Public documents
    * Remain filed in the appropriate committee folder
    * Made public with the "Publish to the web" feature (found in the File Menu when the document is open
    * Shared or copied into the appropriate folder (eg. board reports remain in the committee, but are published and then shared to the Board Meeting Minutes folders)

Thoughts?

**Comment by KrisRecoveryDharma** [comment]
So, I am retracting the earlier request to create three separate drives. 
I apologize for the confusion of transitioning.
