### ISSUE TITLE
Uninstall Slack's GitHub App from `rdcollective` Slack

### ISSUE THREAD

**Issue by nutjob4life** [RecoveryDharma/Infrastructure#4]
The Slack GitHub app is no longer relaying notices on new issues, changes to issues, etc., to Slack. I've uninstalled Slack from GitHub. Now I need **whoever the admin is of the `rdcollective` Slack** to also uninstall GitHub from Slack so we can start over and try again.

To do so:

1. Visit https://rdcollective.slack.com/apps using a _desktop browser_
2. Click "Manage" near the upper-right
3. Click the "Installed apps" tab
4. Click "GitHub" with its "octocat" icon
5. Click "Settings"
6. Click "Workspace access" on the left
7. Click "Uninstall app"

Thank you!

![Screen Shot 2020-09-30 at 11 15 02 AM](https://user-images.githubusercontent.com/814813/94711873-52e38500-030e-11eb-9aa3-142546012162.png)

**Comment by catpanclub** [comment]
Done.

**Comment by nutjob4life** [comment]
Thank you @catpanclub! 🎉
