### ISSUE TITLE
1st Draft: Information Technology Orientation for new Board Members

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#5]
## 🤔 Tell Us About the Feature

Draft of the Information Technology policies and procedures for board members has been started. 
https://docs.google.com/document/d/1O82KhdNnrNd0Ks9iFsS7RmsN6ikPxfHgc8vYaR1UzcA/edit?usp=sharing

## 🎉 What Solution You'd Like

Sean and Dirk review the document and made comments or suggested edits. 

## 〽️ Alternative Ideas

If there are any differences of opinion in the comments or suggested edits, then set up a time to discuss by phone in thenext week or two. 

## 🗺 Context

We want and need this in place for our current functioning. We also want to have something available when new board members are seated in a few months.

**Comment by nutjob4life** [comment]
Hi @KrisRecoveryDharma, @catpanclub; I left some comments in the above-linked doc.

**Comment by catpanclub** [comment]
I have also reviewed/edited/commented.
