### ISSUE TITLE
New Email: Nomination@

### ISSUE THREAD

**Issue by KrisRecoveryDharma** [RecoveryDharma/Infrastructure#8]
Hello,

Please create a new email address: nomination@recoverydharma.org 
Connect it to roehlkris@gmail.com

Thank you!

Kris Roehling

**Comment by catpanclub** [comment]
Done.

**Comment by KrisRecoveryDharma** [comment]
Update:  Please ensure that @Lacey-boop  has access to the nomination@recoverydharma.org email address. She will be monitoring the mailbox while I am on retreat.   However the IT recommends that works is fine with me - changing the linked address or sharing the login information. 

Thanks!

Kris
