### ISSUE TITLE
Non-board account "kelly@recoverydharma.org" still active

### ISSUE THREAD

**Issue by nutjob4life** [RecoveryDharma/Infrastructure#9]
While setting up Google Drive Embedder for Wordpress, I needed to get an API key from G Suite Developer's Console. I noticed that `kelly@recoverydharma.org` was still active and I could log in.

Could someone terminate that account :skull: :gun:  with extreme prejudice? :grin:?

**Comment by catpanclub** [comment]
User kelly@rd.org has been deleted.
